### ISSUE TITLE
test

### ISSUE THREAD

**Issue by yugalme** [yugalme/yugal1#238]
test

Event:
Booking exception: City: Bora Bora, French Polynesia Hotel: Le Meridien#012Traceback (most recent call last):#012File "/root/jatin/harshil/views.py", line 16, in index#012    raise KeyError#012KeyError

Permalink:
https://fegen11.gen3.qa.loggly.net/search#terms=&from=2018-03-01T09:46:58.309Z&until=2018-03-08T09:46:58.309Z&source_group=

**Comment by yugalme** [comment]
test


Event:
Booking exception: City: Bora Bora, French Polynesia Hotel: Le Meridien#012Traceback (most recent call last):#012File "/root/jatin/harshil/views.py", line 16, in index#012    raise KeyError#012KeyError


Permalink:
https://fegen11.gen3.qa.loggly.net/search#terms=&from=2018-03-01T09:46:58.309Z&until=2018-03-08T09:46:58.309Z&source_group=

**Comment by yugalme** [comment]
test


Event:
Booking exception: City: Bora Bora, French Polynesia Hotel: Le Meridien#012Traceback (most recent call last):#012File "/root/jatin/harshil/views.py", line 16, in index#012    raise KeyError#012KeyError


Permalink:
https://fegen11.gen3.qa.loggly.net/search#terms=&from=2018-03-01T09:46:58.309Z&until=2018-03-08T09:46:58.309Z&source_group=
